name: Foundry Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test-fixes
    paths:
      - "TNLS-Gateways/public-gateway/**"
      - ".github/workflows/Foundry_tests.yml"

jobs:
  tests:
    name: TNLS eth gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        working-directory: TNLS-Gateways/public-gateway
        run: forge install

      - name: Run tests
        working-directory: TNLS-Gateways/public-gateway
        run: forge test -vvv

      - name: Check gas snapshots
        run: forge snapshot --check
